### PR TITLE
New Feature: getFilteredPairwiseByTags

### PR DESCRIPTION
**Pull request by julien-boudry**
A new method destined for the Internal Module API
```php
Election->getFilteredPairwiseByTags(string|array $tags, bool $with = true): Pairwise
```

A new method destined for the Public API
```php
Election->getExplicitFilteredPairwiseByTags(string|array $tags, bool $with = true): array
```

replace #151
@LiamM32

### CODE REVIEW

**Comment by LiamM32** [comment]
Yay! Does this work yet in the dev-4.5 branch?

**Comment by julien-boudry** [comment]
> Yay! Does this feature already work?

Yes. But not yet on the dev-4.5 branch, use this branch to merge instead (edit composer.json to change the branch).

I waiting feedback before merging. Also, it's not sure that API is definitive.

**Comment by julien-boudry** [comment]
@LiamM32 some changes, don't know if you have started to integrate. But should be without effect.
It's now ready directly into dev-4.5 branch

**Comment by LiamM32** [comment]
I have tested it in my project. The new function doesn't seem to be working. From `src/Method/EurovisionSchulze.php` in Eurovision_Condorcet:
```
foreach ($contest->votingCountries as $country) {
    //$this->filteredPairwise[$country] = $contest->getResult(methodOptions: ['%tagFilter' => true, 'withTag' => true, 'tags' => $country])->pairwise;
    $this->filteredPairwise[$country] = $contest->getFilteredPairwiseByTags($country);
```
The output has numerous warnings for for various lines in that file, that all say a variation of this:
```
PHP Warning:  Trying to access array offset on value of type null in /home/liam/src/Eurovision_Condorcet/src/Method/EurovisionSchulze2.php on line 28
```
I get many of these for lines 41, 42, 28, & 29.

**Comment by julien-boudry** [comment]
Maybe open a different issue, most probably on your project.

Be careful, before with `$contest->getResult-...)->pairwise` you were working with explicit pairwise.  $contest->getFilteredPairwiseByTags($country); give you a pure Pairwise object (not an array), indexed by candidate key (not candidate's names).

If you want to make a smoother transition, you can first try getExplicitFilteredPairwiseByTags() method, the return has the same format as the previous. Then migrate to the low level and faster getFilteredPairwiseByTags method.

**Pull request merged**
