### PR TITLE
Implement infection/infection

### PR DESCRIPTION
**Pull request by toddy15**
This pull request is for discussion and tracking progress of infection/infection.

### CODE REVIEW

**Comment by julien-boudry** [comment]
Hi @toddy15 ,

I haven't had time to review the changes yet. I will do it soon.

If there are opportunistic improvements: they should be available everywhere.
There might also be a lot of very subtle things, especially when it comes to algorithms.
Also, there will be also some unnecessary things to fix.
I'll try to keep some stats as the commits come in.

Another point, why this new docker file? Why not. But originally the first Dockerfile was mostly made for quick command-line use. For the dev, you just have to create your own image/container and use the shared volumes (not a copy) if needed.
At least, we could move this Dockerfile in the Dev. folder, but I'm a bit circumspect on its usefulness. Also, instead of basing it on php:8.1 it could be based directly on Condorcet, to avoid redundancy.

**Comment by toddy15** [comment]
I've shorten the Dockerfile, thanks for the hint. If you don't think it's useful, you can remove it altogether as well.

The mutant testing is really interesting, and results mostly in more (and better) tests, so that the expected behaviour is thoroughly tested. Sure, some tests are probably not needed. But so far I think that the tests add some value. Some of them are unit tests rather than feature tests, but those are also sensible, I think.

**Comment by julien-boudry** [comment]
Excellent!

**Review by julien-boudry — APPROVED** [review]

**Comment by julien-boudry** [comment]
@toddy15 
Just merge the PR to dev-3.2, but the work is not finished yet. I had many commits, including a preliminary review of mutants from voting methods. I have got some, and find per accident a serious bug in KemenyYoung implementation (but improbable in pratice). But most of them are really difficult to investigate, find the right test...

I will continue with opportunistic tentatives with the rest of the code.

Also, I thought about removing methods visibility mutants, they are very numerous and always absurd.

ps: have a look at the news instructions for Infection on Dev folder, the history, and logs directory.

**Comment by julien-boudry** [comment]
If you want, you can continue on the same infection branch, she is still active. And opening a new pull request.

**Pull request merged**
