### PR TITLE
New Exceptions System

### PR DESCRIPTION
**Pull request by julien-boudry**

### CODE REVIEW

**Comment by toddy15** [comment]
Hi @julien-boudry,

I've now pushed a few new exceptions to this branch. It would be great if you could take a look and tell me if the code is fine with you. It would be a pity if I'm running in the wrong direction. :smile:

Regards,
Tobias

**Comment by julien-boudry** [comment]
> 
> 
> Hi @julien-boudry,
> 
> I've now pushed a few new exceptions to this branch. It would be great if you could take a look and tell me if the code is fine with you. It would be a pity if I'm running in the wrong direction. 😄
> 
> Regards,
> Tobias

Hi @toddy15 

* I just push a new commit: Just add a new class CondorcetPublicApiException as a base abstract class. Actually, it's just providing the trait CondorcetVersion && Stringable interface. But can be useful for the future.

* Maybe we can classify Exception in a subpath (folder & namespace), but it can be done easily later (thx IDE).

* Most of the new test class are not useful, and looks likes duplicate code because they are all the same and without any surprise or risks. Because they don't test the new Exception in action (functional test do it). Maybe we can just add a new expectExeptionMessage() directly into the functional test instead.

**Comment by julien-boudry** [comment]
Another problem with the tests: We cannot know if the coverage is correct on the real tests, because we test each class even if not used in the real world (or lack of real tests).

Instead, I propose to eliminate these unnecessary tests. And to write them only if there were special cases to test that are not satisfied in the functional tests, or if there are features specific to certain Exception classes, which is not the case here, they do not have their own code.

**Comment by julien-boudry** [comment]
Have a look on 9285652 
I think this may be the right model. And easy to apply to others. Don't define the message systematically in the code when it can be defined in the class (but be able to do it for the ones that fit), while being able to pass simple parameters easily.

This should be applied to the others and the following ones.
Do not hesitate to comment.

**Comment by toddy15** [comment]
Hi @julien-boudry,

thanks for your input. Yes, you're right, the new tests I've added provide very little confidence. Basically, they just assure that the exception classes are instantiable and of the correct type. However, the functional tests give more confidence. I'm fine with deleting all those new tests and add some more 'asserts' to the functional tests. So your commit f357935a31d895d32216fde1d20145c3bb48d04a is alright with me.

About adding the abstract class CondorcetPublicApiException: I like that a lot, and in fact, I did think about this already before you've mentioned it. I thought that it might make sense to convert the previous "CondorcetException" to the new exception system and then, when there are no "exception codes" left in CondorcetException, use that as the base class. This way, code using the library would not have to be rewritten for v3.2.0, because they still can catch the generic "CondorcetException". On the other hand, it might be better with the new class you've introduced, because it's a clear break for downstream projects, so hopefully there won't be silent bugs because the downstream author still relies on the old exception system.

Hm, not quite sure about the best approach here.

**Comment by julien-boudry** [comment]
I was thinking about keeping CondorcetException class as a base class, but the constructor is different and it is boring to keep compatibility for the same class. So I create a new one.

I probably plan to have a requirement (for Condorcet 3.2) with PHP 8.1. Wich is an explicit compatibility break.
Of course, Condorcet 3.1 will continue to receive support.  But it's a volunteer project, so I don't really care about backward compatibility, because it's a hobby. And the community is almost non-existent. No one is funding this effort to make sure about compatibility. So let's be radical for the better.

**Comment by toddy15** [comment]
Alright, now I've removed the generic testcases and added more expectations for the exceptionMessage to the functional tests. Is this the way you intended?

**Comment by julien-boudry** [comment]
That's great :)

**Comment by toddy15** [comment]
Hi @julien-boudry,

this branch has seen quite a bit of progress, there are not much old exceptions left. I was wondering how you'd like to merge this branch -- should it be merged into dev-3.2? Because I'm afraid that there will be some conflicts with the other WORK branch with PHP8.1 features.

Would you like me to merge php81 into newExceptions to keep the conflicts to a minimum? After all, the newExceptions branch targets PHP8.1 as well.

**Comment by julien-boudry** [comment]
Hi @toddy15,

The conflicts will be really easy to solve, for almost all of them (if not all) it will be about the new type of return "never" in the tests that have changed names.

Il will do it myself, after reviewing the last Exception migrations. Are you ready yet to works with PHP 8.1?

**Comment by toddy15** [comment]
Hi @julien-boudry,

yes, the majority of conflicts is about the return type. However, some merge conflicts are due to some typo fixes I did in method names. If you agree, I could also fix those typos in the branch php81, that will make the merging easier.

About PHP 8.1: I'm using Debian on my computer, and unfortunately, the installed version of PHP is still at 7.4. Once the new PHP version will be available, it'll be 8.0. So I have to work around this limitation. Currently, I'm using your Dockerfile. I've tweaked it a bit so I can run phpunit on the current branch within docker. It would be trivial to switch the Dockerfile to PHP 8.1, so yes, I can work with PHP 8.1.

**Comment by julien-boudry** [comment]
Hi @toddy15,

Yes, it's easy with Docker, I do it myself with shared volume, directly from official PHP images.

I will do the merge from dev-3.2 branch (wich have merged few hours ago with php 8.1) into newExceptions branch.

**Comment by julien-boudry** [comment]
Merged!

**Comment by toddy15** [comment]
Great, thanks! The branch is now almost ready to be merged into dev-3.2, there are only a couple of minor thing to fix. In some places of the code, the CondorcetException is still used.

**Comment by julien-boudry** [comment]
> 
> 
> Great, thanks! The branch is now almost ready to be merged into dev-3.2, there are only a couple of minor thing to fix. In some places of the code, the CondorcetException is still used.

Yes, the last ones are harder to fix, because maybe some of them need some new tests (actually, only coverage is lower, for example with Vote.php).

**Comment by julien-boudry** [comment]
Thanks for all! I will see the problem with the Vote class tomorrow.

**Comment by toddy15** [comment]
Soo ... I think that I've spotted every left over occurence of CondorcetException now, apart from some places in Documentation -- but as I understand it, you generate those files, right?

So from my perspective, this branch could be merged into dev-3.2.

**Comment by julien-boudry** [comment]
Very nice job @toddy15!

If you wants to continue to contribute, you can have a look at issues (or submit any ideas):
https://github.com/julien-boudry/Condorcet/issues
https://github.com/julien-boudry/Condorcet/projects/1

**Comment by toddy15** [comment]
Hi @julien-boudry,

thanks! Indeed, I'd be interested in looking into the infection/infection implementation (#53).

Apart from that, have you heard of https://pestphp.com/? It seems to be a really nice testing framework, capable of running the standard PHPUnit tests. However, the tests are much nicer to read and write -- at least in my opinion.

**Comment by julien-boudry** [comment]
Let's continue in the discussion section. And a new pull request for Infection.

**Pull request merged**
