### PR TITLE
Rebuild exception system

### PR DESCRIPTION
**Pull request by toddy15**
Hi @julien-boudry,

I've read in your README (under Roadmap for further releases) that you'd like to rebuild the exception system. I'm not sure what you have in mind, but I assume that you'd like to create specialized exception classes instead of the generic CondorcetException. I'm not sure if my interpretation is correct, though. So in order to not make a lot of work without any gain, I've gone ahead and created a minimal working example. 

I've created only one new exception as an example (VotingHasStartedException). Please take a look at this implementation and tell me if this is the right direction. If so, I could incrementally rework the current exception system.

If this is not what you have in mind, just discard and close this PR. :smile:

Regards,
Tobias

### CODE REVIEW

**Comment by julien-boudry** [comment]
Hello @toddy15!

Thanks for your interest. And I'll be interested to know what uses you make (or plan to) of Condorcet.

It is indeed an old note. The idea was vague, but more or less instinctively was to :

- [ ] Harmonize error codes (and by which standard?)
- [x] Use a maximum of exceptions instead of returning false
- [x] Separate Throwable into public API Exceptions, internal ones (CondorcetInternalException) or even errors (CondorcetInternalError)
- [ ] Possibly create subclasses of Exceptions, which corresponds to your idea. But the practical interest didn't jump out at me, especially since this is not the most fun part to code)

Your solution seems elegant, I like it. If you're motivated, we could actually put this on a dedicated branch, and I'll help.

One question: But what about the Throw attribute? With the idea of generating documentation?

**Comment by toddy15** [comment]
Yes, I'd like to tackle this incrementally, so a dedicated branch seems fine to me.

The Throws attribute is just for documentation, right. As with all other attributes, it formalizes the "@throws" annotation which people used with PHPDoc. Alternatively, I could add

```
/**
 * @throws VotingHasStartedException
 */
```
at the top of the function.

**Comment by toddy15** [comment]
... oh, and about my use of Condorcet: I'm member of a (very) small non-profit organization and we've used your library for an internal vote (Schulze method).

**Comment by julien-boudry** [comment]
_(Maybe Condorcet can become a Debian package, one day. _I see your email address_)_

I'll think about all this by tomorrow (including the workflow). 

You can go on like this for now. The most fastidious part is to replace the calls scattered in the code and tests.

Leave it like that for the documentation. The day we will have a PSR for the doc. using PHP8 attributes, I will adapt them, in the meantime, we stay on custom. You can indeed create this new attribute, I can use it later in the generator.

**Comment by toddy15** [comment]
Well, for the Debian package: why not? However, I've never packaged a PHP application/library, so I need to dig into that. And by the way, Debian is **not** the very small NPO I was talking about :smile: – although I knew the Schulze method from there, because Debian also uses that voting system for their internal votes.

I'll wait until you've thought about this, no hurry.

**Comment by julien-boudry** [comment]
> Well, for the Debian package: why not? However, I've never packaged a PHP application/library, so I need to dig into that. And by the way, Debian is **not** the very small NPO I was talking about :smile: – although I knew the Schulze method from there, because Debian also uses that voting system for their internal votes.
> 
> I'll wait until you've thought about this, no hurry.

I thinking about the command line version, not the library. It's maybe possible for the next stable, but it's another thread ;)

**Comment by julien-boudry** [comment]
New Pull request on #60

**Comment by toddy15** [comment]
Great, thanks! I will clone the repo and start working on that branch.

**Pull request merged**
